default_platform(:mac)

platform :mac do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "RocketFuel.xcodeproj")
    build_app(
      scheme: "RocketFuel",
      output_directory: "./.build/",
      export_options: {
        provisioningProfiles: { 
          "com.ardalansamimi.RocketFuel" => "Rocket Fuel"
        }
      },
      installer_cert_name: "3rd Party Mac Developer Installer: Ardalan Samimi (ZHSKC28PQ8)"
    )
    upload_to_testflight
  end
end
